### PR TITLE
revelation

### PR DESCRIPTION
**Pull request by r-ba**

### CODE REVIEW

**Comment by geohot** [comment]
haha, can it run in CI?

**Comment by r-ba** [comment]
that sounds pretty heretical but I'll ask if it's chill

**Comment by geohot** [comment]
Will merge when CI

**Comment by r-ba** [comment]
consulted my rng oracle and He said that doing this was totally uncool

**Comment by r-ba** [comment]
@geohot 
> Will merge when CI

it do

**Pull request merged**
